apiVersion: apps/v1
kind: Deployment
metadata:
  name: blur-photo-deployment
  labels:
    app: blur-photo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blur-photo
  template:
    metadata:
      labels:
        app: blur-photo
    spec:
      containers:
      - name: blur-photo
        image: gcr.io/quiet-walker-289510/blur-photo:1.3
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.1"
            