apiVersion: v1
kind: Service
metadata:
  namespace: blur-photo
  name: blur-photo
spec:
  type: LoadBalancer
  selector:
    app: blur-photo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000